### ISSUE TITLE
markup for dead links

### ISSUE THREAD

**Issue by RonnieMarksch** [ho-tex/hyperref#1]
Please consider the following "patch" by Ulrike Fischer ( 18z5slyob7qvb.dlg@nililand.de ) for markup of dead links.
Maybe \color{red} #3 is just fine for some color provided by the user.

https://de.comp.text.tex.narkive.com/r7OOusMU/hyperef-farbe-fur-tote-links

```
\documentclass{article}
\usepackage{xcolor}
\usepackage{hyperref}

\makeatletter
\def\label@@hyperref#1#2#3{%
  \ifx#1\relax
    \protect\G@refundefinedtrue
    \@latex@warning{%
      Hyper reference `#2' on page \thepage \space undefined%
    }%
    \begingroup
      \colorbox{yellow}{\color{red}\bfseries #3}%was auch immer
    \endgroup
  \else
    \hyper@@link{\expandafter\@fifthoffive#1}%
      {\expandafter\@fourthoffive#1\@empty\@empty}{#3}%
  \fi
}
\makeatother
\begin{document}

\hyperref[target]{text}

% \label{target}

\end{document}
```

**Comment by davidcarlisle** [comment]
@u-fischer , @RonnieMarksch   do you think it would be enough to define

 `\let\hyperefundefinedlink\@firstofone` 

and use 

`\hyperrefundefinedlink{#3}` 

that a user could  redefine that command how they wish, or is it worth adding some keyval interface to define the formatting?

Also was this issue raised on a public list somewhere originally?
