### ISSUE TITLE
hyperref causes a vertical shift of print space after dvips

### ISSUE THREAD

**Issue by kberry** [ho-tex/hyperref#10]
(reposted from https://puszcza.gnu.org.ua/bugs/index.php?166, author    Ulf Rehmann <rehmann>)

Hi,

The attached (essentially minimal) tex file can demonstrate a bug in hyperref or in the driver dvips.

While the dvi file produced by latex looks correct, the ps file derived from that dvi file by 'dvips -t a4 ...' (or similar) shows a vertical downshift of the print space (Satzspiegel). The same holds for the pdf file, derived from the latter by ps2pdf, say.

This vertical shift does not appear when the line '\usepackage{hyperref}' is commented out.

File list produced by \listfiles see below.

Thanks for any help.

Best regards,
Ulf Rehmann

File List
article.cls 2007/10/19 v1.4h Standard LaTeX document class
size10.clo 2007/10/19 v1.4h Standard LaTeX file (size option)
hyperref.sty 2009/10/09 v6.79a Hypertext links for LaTeX
keyval.sty 1999/03/16 v1.13 key=value parser (DPC)
ifpdf.sty 2009/04/10 v2.0 Provides the ifpdf switch (HO)
ifvtex.sty 2008/11/04 v1.4 Switches for detecting VTeX and its modes (HO)
ifxetex.sty 2009/01/23 v0.5 Provides ifxetex conditional
hycolor.sty 2009/10/02 v1.5 Code for color options of hyperref/bookmark (HO
)
xcolor-patch.sty 2009/10/02 xcolor patch
pd1enc.def 2009/10/09 v6.79a Hyperref: PDFDocEncoding definition (HO)
etexcmds.sty 2007/12/12 v1.2 Prefix for e-TeX command names (HO)
infwarerr.sty 2007/09/09 v1.2 Providing info/warning/message (HO)
hyperref.cfg 2002/06/06 v1.2 hyperref configuration of TeXLive
kvoptions.sty 2009/08/13 v3.4 Keyval support for LaTeX options (HO)
kvsetkeys.sty 2009/07/30 v1.5 Key value parser with default handler support
(HO)
url.sty 2006/04/12 ver 3.3 Verb mode for urls, etc.
bitset.sty 2007/09/28 v1.0 Data type bit set (HO)
intcalc.sty 2007/09/27 v1.1 Expandable integer calculations (HO)
bigintcalc.sty 2007/11/11 v1.1 Expandable big integer calculations (HO)
pdftexcmds.sty 2009/09/23 v0.6 LuaTeX support for pdfTeX utility functions (
HO)
ifluatex.sty 2009/04/17 v1.2 Provides the ifluatex switch (HO)
ltxcmds.sty 2009/08/05 v1.0 Some LaTeX kernel commands for general use (HO)

atbegshi.sty 2008/07/31 v1.9 At begin shipout hook (HO)
hdvips.def 2009/10/09 v6.79a Hyperref driver for dvips
pdfmark.def 2009/10/09 v6.79a Hyperref definitions for pdfmark specials
nameref.sty 2007/05/29 v2.31 Cross-referencing by name of section
refcount.sty 2008/08/11 v3.1 Data extraction from references (HO)
test.out
test.out

---

(no files were attached; i'm following up with the author --karl)

**Comment by u-fischer** [comment]
I'm closing this as without an example it is not possible to reproduce it.  Feel free to repost if more info a available.
