### ISSUE TITLE
luatex driver should use unicode by default

### ISSUE THREAD

**Issue by u-fischer** [ho-tex/hyperref#101]
without it one gets (at least in the adobe reader) wrong bookmarks:

~~~~
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\tableofcontents
\section{Straße}
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/63940395-ad564600-ca69-11e9-9959-6e866b033530.png)

**Comment by e-kwsm** [comment]
```diff
-\usepackage{hyperref}
+\usepackage[unicode]{hyperref}
```

**Comment by u-fischer** [comment]
Sorry? Yes I know that I can activate the option in the document, but imho it should be the default. (The issue is only a reminder to myself).

**Comment by e-kwsm** [comment]
Ah sorry, I didn't read the issue title properly.
