### ISSUE TITLE
[doc] Change description of dvipdfmx's default pdf version

### ISSUE THREAD

**Issue by muzimuzhi** [ho-tex/hyperref#104]
Currently, the doc of hyperref says
https://github.com/ho-tex/hyperref/blob/ecaccfba8d8823076a9f425e92767ec990514f2b/doc/manual.tex#L1677-L1679

But dvipdfmx has changed to generate pdf 1.5 by default, since 2010, May. This can be checked from output of executing `dvipdfmx -help`, and from the [changelog of dvipdfmx](https://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/ChangeLog?revision=52052&view=markup#l2579).

Hence the above lines of doc could be changed to something like
```latex
 \item The PDF version should be at least 1.5. It is automatically
    set both for pdfTeX and dvipdfmx (since 2010, May).
```

**Comment by davidcarlisle** [comment]
Thanks for the comment.
