### ISSUE TITLE
Checkboxes do not appear in some PDF viewers

### ISSUE THREAD

**Issue by kberry** [ho-tex/hyperref#12]
(reposted from https://puszcza.gnu.org.ua/bugs/index.php?153, author Mike <mike>)

Checkboxes in the PDF form that I'm creating do not show up in Preview.app or Adobe Reader on OS X 10.7. My cursor changes if I mouse over where the box should be, and if I click on it I can even see the briefest flicker of the box and checkmark. Both promptly disappear.

In Adobe Reader on Windows, the checkboxes are initially invisible, but show up the first time I click on them. In FoxIt Reader they work exactly as expected.

I have attached examples of my TeX source, the PDF output, and a screenshot of what the PDF looks like when I open it.

There is a discussion of this issue on StackExchange: http://tex.stackexchange.com/questions/32810/checkboxes-in-pdf-forms-dont-show-up-in-os-x

-- comment 1:

I confirm this problem in evince 3.4.0 for linux (ubuntu 12.04). \CheckBox creates working checkboxes in acroread (print only, no save), PDF-XChange Viewer, and okular but NOT in evince. (The mouse changes on hover but no check appears on click. The document registers an edit because evince displays the save options on closing.)

I also filed this as an evince bug, but evince does handle PDF checkboxes created with other form editors (such as OpenOffice).

Best,
Michael

![screenshot2011-10-27at8 44 11pm](https://cloud.githubusercontent.com/assets/362855/15370353/7bf191fc-1ceb-11e6-989c-3ec2053f239e.png)
[test.pdf](https://github.com/ho-tex/hyperref/files/271132/test.pdf)
[test.tex.txt](https://github.com/ho-tex/hyperref/files/271133/test.tex.txt)

**Comment by u-fischer** [comment]
That's a quite old bug report and it is quite unclear if it still valid. This input works fine for me on windows 7 with a current Adobe reader (compiled with xelatex and pdflatex)

```
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\begin{Form}
\CheckBox{Test} Test:\CheckBox[name=Foo]{}
\end{Form}
\end{document}
```

In the one answer in the tex.sx discussion the syntax `\CheckBox{}` is imho faulty: Form fields needs a name, by default hyperref uses the label as the name and this means that empty labels are problematic and requires the use of the `name` key.

**Comment by u-fischer** [comment]
I'm closing the issue as unclear if still relevant.
