### ISSUE TITLE
link rectangle too small with (x)dvipdfmx

### ISSUE THREAD

**Issue by kberry** [ho-tex/hyperref#15]
with the document below and everything from the TL16 pretest (or earlier versions, this is not new), process with xelatex (hence xdvipdfmx), the "link rectangle" as displayed by xpdf around the text "J.exam.or" is too tight -- right up against the black pixels in every dimension.  same results with latex|dvipdfmx.

process with pdflatex, there is a small but better-than-nothing margin.

\documentclass{article}
\usepackage{hyperref}
\begin{document}
\href{foo}{J.exam.or}
\end{document}

i know it could be, maybe even probably is, something in (x)dvipdfmx. i know its algorithm for computing that link rectangle is necessarily completely different from pdftex's.

however, i see various kludge factors in hyperref specifically relating to the link rectangles for the (x)dvipdfm(x) backend, although i admit i could not easily discern what they all were and what they were supposed to do. therefore i wondered if it is something at the hyperref level.

would you mind taking a look?  thanks.

**Comment by u-fischer** [comment]
You can change the link margins in pdflatex through `\pdflinkmargin` but this is not possible with the xdvipdfmx-driver. See also http://tex.stackexchange.com/a/77595/2388.

**Comment by kberry** [comment]
thanks ulrike. my main point was that the default result for the (x)dvipdfm(x) link rectangle is  bad, inferior to pdftex's.  i remain unsure whether it is something to be addressed in hyperref or (x)dvipdfm(x).  

my first cursory look at the d*fmx C code in this area seemed like it was using the tfm metrics to compute link rectangle, which should not have a clipped-to-the-black-ink result.

**Comment by shreevatsa** [comment]
> unsure whether it is something to be addressed in hyperref or (x)dvipdfm(x).

I think this may be something to be addressed in (x)dvipdfm(x):

- For pdfTeX, hyperref uses the `\pdflinkmargin` primitive of pdfTeX, and sets it to `1pt` by default. (pdfTeX's default is 0pt, hyperref's default is 1pt)
- For dvipdfm, hyperref simply inserts `pdf:bann` … `pdf:eann` specials, and it is dvipdfm (or whatever) that computes the size of the boxes.

Note that for the minimal file [above](https://github.com/ho-tex/hyperref/issues/15#issue-157793401), if one generates the PDF as follows:
```
xelatex --no-pdf mwe.tex
dvipdfmx -g 1pt mwe.xdv
```
then in the resulting PDF, the horizontal margins seem to be similar to that in the PDF file generated with `pdflatex mwe.tex`. (This `-g` is `Annotation "grow" amount`, mentioned [here](https://www.tug.org/TUGboat/tb30-1/tb94cho.pdf). So I think one could just change the default config file, to improve the results for all users.)

When I view these in Acrobat Reader, the link generated by xdvipdfmx is inferior in a different way: in the vertical dimension, they are much too large, and can intersect link rectangles from the previous/next line. I don't know where that problem originates. (I noticed all this while writing [this answer](https://tex.stackexchange.com/questions/391004/link-boxes-obscure-punctuation/392061#392061).)

**Comment by u-fischer** [comment]
The default behaviour is now much better:

Old:
![image](https://user-images.githubusercontent.com/4047173/48940623-a4ec4000-ef18-11e8-82b0-9991025e418d.png)

New (texlive 2018):
![image](https://user-images.githubusercontent.com/4047173/48940645-b897a680-ef18-11e8-9423-fe878d50ba9b.png)

(x)dvipdfmx also has now a special which allows to globally encrease the spacing in the document:

~~~~
\documentclass{article}
\usepackage{hyperref}
\special{dvipdfmx:config g 10}

\begin{document}
\href{foo}{J.exam.or}
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/48940742-07ddd700-ef19-11e8-8ed3-976ce327c579.png)

One could probably map the option `pdflinkmargin` for dvipdfmx to this special - the behaviour is not identical but near enough.

**Comment by u-fischer** [comment]
Done in https://github.com/ho-tex/hyperref/commit/000d28c92e429c071e86dbfd3de66aef9ccecd0f
