### ISSUE TITLE
No hyperlink created when using \hyperlink and \phantom with xelatex

### ISSUE THREAD

**Issue by xduugu** [ho-tex/hyperref#16]
I noticed this issue when trying to use the acro package. Creating links to the acronyms list works with pdflatex, but not with xelatex.

Clemens Niederberger posted a [MWE](https://bitbucket.org/cgnieder/acro/issues/76/hyperref-option-does-not-work-with-xelatex#comment-28543118), which shows that the issue is in the hyperref package.

```
% arara: xelatex
% arara: xelatex
\documentclass{article}
\usepackage{hyperref}

\begin{document}

\hypertarget{name}{text}
\clearpage
\hyperlink{name}{\phantom{text}}text

\end{document}
```

**Comment by agrahn** [comment]
This is a `(x)dvipdfmx` peculiarity which can hardly be fixed on the TeX-level. The `pdf:bann` and `pdf:eann` specials for creating line-breakable PDF annotations require typeset glyphs in between to compute a non-zero annotation rectangle.

**Comment by xduugu** [comment]
I worked around this issue by using a different package for acronyms. If it is not fixable, feel free to close this issue.

**Comment by u-fischer** [comment]
hyperref provides a command `\XeTeXLinkBox` which can be used to get a link box with xelatex (it inserts small space glyphs):

```
\documentclass{article}
\usepackage{hyperref}

\begin{document}

\hypertarget{name}{text}
\clearpage
\hyperlink{name}{\XeTeXLinkBox{\phantom{text}}}text

\end{document}
```

**Comment by davidcarlisle** [comment]
@u-fischer  do you think it would be possible to detect the need for `\XeTeXLinkBox`  automatically? Or I wonder if a feature request could be made for (x)dvipdfm(x) to give a bit more help in the case the glyph based size heuristic returns no sensible values.

**Comment by u-fischer** [comment]
@davidcarlisle  I don't really see how xetex should be able to check if the box contains glyphs or not, at least not on the macro level. Imho the problem should be solved in xdvipdfmx.

**Comment by u-fischer** [comment]
I did send a bug report to the dvipdfmx mailing list and close here.
