### ISSUE TITLE
pdfauthor and pdftitle 'eat away' last char

### ISSUE THREAD

**Issue by stdedos** [ho-tex/hyperref#18]
Mn-WE included: [lipsum.zip](https://github.com/ho-tex/hyperref/files/386245/lipsum.zip)

Buggy Code In Question:
`\newcommand{\AuthorName}{Ntentos Stavros}`
`... pdftitle={Thesis of \AuthorName}, pdfauthor={\AuthorName} ...`

produces 
![image](https://cloud.githubusercontent.com/assets/133706/17177933/288d0f7e-541c-11e6-80e6-1a5d952335c3.png)

If we include in the `\newcommand{\AuthorName}{Ntentos Stavros}` anything (a letter, an unbreakable space "\ ", even a "breakable space", ie " "), the output is:

![image](https://cloud.githubusercontent.com/assets/133706/17177989/5e9aaf54-541c-11e6-98c4-ad857dfeb55f.png)

**Comment by stdedos** [comment]
*This still holds true if the change is done on the `... pdftitle={Thesis of \AuthorName}, pdfauthor={\AuthorName} ...` section

**Comment by davidcarlisle** [comment]
That's odd, but I tried your file with texlive 2016 and did not see any truncation of the fields either in acrobat or pdfinfo.

pdfinfo reported:


```
$ pdfinfo lipsum.pdf
Title:          Thesis of Ntentos Stavros
Subject:        ThesisTitle
Keywords:      
Author:         Ntentos Stavros
Creator:        Ntentos Stavros
Producer:       pdfTeX-1.40.17
CreationDate:   Wed Jul 27 15:43:12 2016
ModDate:        Wed Jul 27 15:43:12 2016
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      595.276 x 841.89 pts (A4)
Page rot:       0
File size:      31995 bytes
Optimized:      no
PDF version:    1.5
```

**Comment by stdedos** [comment]
I even updated MikTex after posting (to make sure it was not a package error, but compiling in TexMaker showed that indeed it wasn't a package error. :disappointed: 

I verify that both are accurate
![image](https://cloud.githubusercontent.com/assets/133706/17179891/75345772-5423-11e6-889e-a0c3430e71b1.png)

Maybe an Adobe Acrobat editor error?

**Comment by josephwright** [comment]
Can you add `\listfiles` to your input and upload your `.log` file? Like @davidcarlisle, I don't see an issue using the MWE and checking using Preview on the Mac, so the PDF itself is I think fine.

**Comment by stdedos** [comment]
There you go. (I think I should've done it in the first place, I am sorry for the delay)

[lipsum.zip](https://github.com/ho-tex/hyperref/files/386377/lipsum.zip)

**Comment by josephwright** [comment]
Do you see the issue if you remove the packages loaded other than `hyperref`?

**Comment by stdedos** [comment]
Yes, no change:
![image](https://cloud.githubusercontent.com/assets/133706/17181611/6bc66cba-5429-11e6-9ea1-355303e9636d.png)

**Comment by josephwright** [comment]
I think this has got to be an issue at the Acrobat end. Can you send me the PDF (joseph.wright@morningstar2.co.uk)? I wonder about localisation: I notice the screenshot shows the times using something that looks a bit like Greek, or at least uses mu!

**Comment by stdedos** [comment]
There goes the PDF:
[lipsum.pdf.zip](https://github.com/ho-tex/hyperref/files/386475/lipsum.pdf.zip)

Yes, indeed - what you see is Greek date / time

**Comment by josephwright** [comment]
Definitely OK at my end so this is 'not us' I'm afraid. My guess is a Acrobat bug.
