### ISSUE TITLE
Error: pdfendlink ended up in different nesting level than \pdfstartlink 

### ISSUE THREAD

**Issue by dolerite** [ho-tex/hyperref#19]
\hyperref works without issues for me in a (bibtex) bibliography set in normal one-column mode.

In two-column mode, it often crashes with the above error. This has been previously reported, e.g.
http://tex.stackexchange.com/questions/265881/pdftex-error-ext4-pdfendlink-ended-up-in-different-nesting-level-than-pd

and is understood to be a problem when a link is broken across a page or column. My bibliography is about 5000 entries covering 100 pages, so any sort of manual fix is out of the question.

Assistance in getting a fix would be greatly appreciated

**Comment by davidcarlisle** [comment]
It would be interesting to know if Heiko's fix in the last few lines of

http://tex.stackexchange.com/a/249743

works for your real example?

David

**Comment by dolerite** [comment]
Hello David,

First, thanks for your swift reply.

Second, and most important, IT WORKS!   In the last year or so I have 
tried any of the proposed fixes that I could find, all without success.

This one fix generates everything correctly for several pages of 
bibliography, all with correct hyperlinks.

To confirm, I simply entered the lines:
---
\usepackage{etoolbox}
\makeatletter
\patchcmd\@combinedblfloats{\box\@outputbox}{\unvbox\@outputbox}{}{%
   \errmessage{\noexpand\@combinedblfloats could not be patched}%
}%
\makeatother
---

Again, with my thanks!

Michael

**Comment by lzkelley** [comment]
This, **extremely frustrating** error pops up for me all the time.  And googling for it shows that it has been an issue for people for **10 years**.  It would be nice if it was just fixed... or at the *very least* the error message could tell you which link is actually being split.

**Comment by davidcarlisle** [comment]
@lzkelley  it would be useful to know since you say you have examples of this if the patch in the comment above works for you.  The error message itself comes from pdftex not hyperref so any change in the message text would need to be requested from the pftex developers.

**Comment by lzkelley** [comment]
@davidcarlisle  Trying the workaround I get the error:

    Undefined control sequence.
    \patchcmd@combinedblfloats{\box@outputbox}{\unvbox@outputbox}{}{%

**Comment by davidcarlisle** [comment]
that was a github formatting issue from the OP's comment try now I've fixed the markdown so the backslashes show. (I hadn't noticed as they show in the email, just not on this site)

**Comment by PABourdin** [comment]
@davidcarlisle The above workaround indeed fixes the issue for me, too, after you corrected the markdown. As this bug is really really annoying and I just wasted some hours to come and find this page, I would very very strongly suggest to finally find the bug within hyperref, if there is any, which I assume. Are you in charge of hyperref development?

Thanks and best greetings.

**Comment by PABourdin** [comment]
@davidcarlisle Is the location and cause of the bug already known? May I help by at least temporarily adding the above work-around into the productive version until a better solution is found? Could you give me a pointer on where to find the offending code?

**Comment by davidcarlisle** [comment]
everything I know about this is in this ticket, sorry!

**Comment by PABourdin** [comment]
I have quickly set up a small test document that also includes the fix to the problem, see comment.
[MWE.txt](https://github.com/ho-tex/hyperref/files/1191809/MWE.txt)

**Comment by u-fischer** [comment]
Moved to https://github.com/latex3/latex2e/issues/94
