### ISSUE TITLE
\href in \contentsline

### ISSUE THREAD

**Issue by norbusan** [ho-tex/hyperref#20]
Dear all,

down here at Debian we got complains that doxygen generated documents cannot be compiled with hyperref (anymore? - I don't know whether it worked before), see http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835162

I have reduced this to the following MWE:
```
\documentclass{article}
\usepackage{hyperref}
\begin{document}

\contentsline{section}{note: \href{http://a.b.c/d#EEE}{link} }{}{}

\end{document}
```

which gives an error when compiled with pdflatex, coming from nameref.sty is my guess.

I am not even sure whether it makes sense to have links in TOC entries, because the TOC entries by themselves are links within the document, but who knows ...

If you have any comments, please let me know.

Thanks

Norbert

**Comment by davidcarlisle** [comment]
I doubt this has changed for years (no time to check the records today,
sorry)
usual problems with "making characters safe" is that it fails if used after
they
are already tokenized.

This works, and doxygen could presumably generate equivalent code

\documentclass{article}
\usepackage{hyperref}
\edef\safehash{\string#}
\begin{document}

\contentsline{section}{note: \href{http://a.b.c/d\safehash EEE}{link} }{}{}

\end{document}

**Comment by norbusan** [comment]
Thanks, perfect, this is what I wanted to hear ("no changes in years").

I think we can close this issue.

Thanks
