### ISSUE TITLE
Href doesn't work with abolute local path in linux

### ISSUE THREAD

**Issue by student-sx** [ho-tex/hyperref#21]
Suppose I have a tex file in a directory called /mytexfiles/texfile.tex which contains a line like

\href{/path/to/my/pdf/file.pdf}{pdf-file}

If I open the compiled document in evince and click on the link, it displays an error message which indicates that evince tries to look at the combined path for the file, i.e. /mytexfiles/path/to/my/pdf/file.pdf so it couldn't open the file.

**Comment by student-sx** [comment]
I just noticed that there is a workaround by using the keyword run: but then something like \href[page=3]{run:/path/to/my/pdf/file.pdf}{pdf-file} doesn't work.

**Comment by u-fischer** [comment]
There is no complete example and the pdf is not available for inspection but imho this is (was) an evince problem. In my tests the annotation looks ok.
