### ISSUE TITLE
No way to specify capitalization

### ISSUE THREAD

**Issue by karyon** [ho-tex/hyperref#22]
The english strings contain e.g. `Figure` and `section`. [http://tex.stackexchange.com/questions/36575/autorefs-inserted-text-has-not-the-correct-case](here) are people that want to write `Figure` with a small letter, and [here](http://tex.stackexchange.com/questions/34155/autoref-does-not-capitalize-initial-character-in-sentence-when-referencing-labe) are other people who want to capitalize `section`.

Since there are obviously different styles in use, it struck me as odd that hyperref has opinionated defaults and no way to override it. Or am I missing something?

**Comment by thomwiggers** [comment]
You can do stuff like `\renewcommand{\sectionautorefname}{Section}`. That's also the way the docs suggest you to do it.

Doing it on a case-by-case basis for sentences is harder.

**Comment by u-fischer** [comment]
Yes, the answers in http://tex.stackexchange.com/questions/36575/autorefs-inserted-text-has-not-the-correct-case show more possible ways to change this.
