### ISSUE TITLE
Modify backref to add a list of where the ref­er­ence was cited, to each bib­li­og­ra­phy en­try similar to hypdvips.sty implementation.

### ISSUE THREAD

**Issue by mjmg** [ho-tex/hyperref#23]
When compiling via latex->dvi->ps->pdf using hyperref, backref and hypdvips, the bibliographic entries are formatted as such:

D. Knuth, The TEXbook. Addison-Wesley Professional, 1984.
(Referenced on pages 16 and 19.)

When using pdflatex it is just:

D. Knuth, The TEXbook. Addison-Wesley Professional, 1984. 16, 19

The relevant code in hypdvips.sty is this:

```
\ifHy@backref
    \ifx\backrefxxx\hyper@section@backref
      \@ifpackageloaded{cleveref}
        {
        \renewcommand*{\backrefalt}[4]{%
          \setlength{\pp@offset}{\baselineskip}%
          \\\scriptsize(Referenced in
          \setlength{\baselineskip}{\pp@offset}%
          ##2.)
          }
        }
        {
        \renewcommand*{\backrefalt}[4]{\\\scriptsize(Referenced\ in: ##2.)}
        }
    \fi
    \ifx\backrefxxx\hyper@page@backref
      \renewcommand*{\backrefalt}[4]{%
        \ifcase##1%
        \or%
          \\\scriptsize(Referenced\ on\ page ##2.)
        \else%
          \\\scriptsize(Referenced\ on\ pages ##2.)
        \fi%
      }
    \fi
  \fi
```

There is a related patch here [https://www.ctan.org/pkg/ut-backref](url)

Can we have the same format output no matter what the compiler used?

**Comment by u-fischer** [comment]
I don't think that it would be a good idea if hyperref would change the default backref format and so change the output of many existing documents. If you want the output of `hypdvips`  then copy the code to your document or you own sty.

**Comment by davidcarlisle** [comment]
agreeing with @u-fischer  that hyperref can not really change this, one possibility would be that hydvips is generalised to be a general extension to hyperref so that it could make the same changes for all driver options.
