### ISSUE TITLE
XeTeX fails with % and non-ASCII characters in headings

### ISSUE THREAD

**Issue by adunning** [ho-tex/hyperref#25]
When combining '%' with a non-ASCII character in a heading, hyperref's output does not work with XeTeX. The following example fails on the second pass when using xelatex:

```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\section{\%á}
\end{document}
```

It gives the following error:

```latex
Runaway argument?
{
! File ended while scanning use of \@@BOOKMARK.
<inserted text> 
                \par 
l.3     \begin{document}
```

To fix this, one can either use `\usepackage[unicode]{hyperref}` or add `\usepackage{bookmark}`. Adding `\hypersetup{unicode=true}` results in the same error.

This problem and the solution was [discussed on StackExchange](https://tex.stackexchange.com/questions/313266/and-non-ascii-characters-in-headings) last year, but it doesn't seem to have been reported here yet.

**Comment by u-fischer** [comment]
Imho this is a bug in hyperref.sty. It is missing a call of `\HyPsd@EscapeTeX#1`  which would excape the comment char (and braces). 

Line 675 to 684 of hyperref.sty looks like this:

```

            \StringEncodingConvertTest\HyPsd@temp\HyPsd@temp
                                      {utf16be}{ascii-print}{%
              \EdefEscapeString\HyPsd@temp\HyPsd@temp
              \global\let#1\HyPsd@temp
              \HyPsd@EscapeTeX#1%
              \Hy@unicodefalse
            }{%
              \HyPsd@ToBigChars#1%
            }%

```

This is inside a `\ifxetex`. hyperref tries to convert something (the section text in this case) from utf16be to ascii-print. If this is possible (if the header contains only ascii) the first branch is taken and everything works. But if there is some non-ascii then ` \HyPsd@ToBigChars#1`  is executed which puts a percentchar in the argument, but in this branch ` \HyPsd@EscapeTeX#1%`  is missing which would replace this percent with something safe. 

Imho the code should be replaced by 

```

            \StringEncodingConvertTest\HyPsd@temp\HyPsd@temp
                                      {utf16be}{ascii-print}{%
              \EdefEscapeString\HyPsd@temp\HyPsd@temp
              \global\let#1\HyPsd@temp
              \HyPsd@EscapeTeX#1%
              \Hy@unicodefalse
            }{%
              \HyPsd@ToBigChars#1%
             \HyPsd@EscapeTeX#1% <--- new
            }%

```

**Comment by eg9** [comment]
See also https://tex.stackexchange.com/questions/117267/strange-bug-with-hyperref-percent-symbol-and-cyrillic-character
