### ISSUE TITLE
the patch of longtable for footnotes does not work if ``\footnote[N]`` form

### ISSUE THREAD

**Issue by jfbu** [ho-tex/hyperref#29]
Example:
```latex
\documentclass{article}
\usepackage{longtable}
\usepackage{hyperref}
\begin{document}
\begin{longtable}[c]{lp{3cm}p{3cm}}
  Hello&Hello&Hello\\
\endfirsthead
\endhead
\endfoot
\endlastfoot
 X
  \footnote[3]{%
    with optional argument in l column
  }
&X
  \footnote[5]{%
    with optional argument in p column
  }
&X
  \footnote{%
    without optional argument in p column
  }
\end{longtable}
\clearpage
Next page
\end{document}
```
The second footnote has wrong number at bottom of page (but the hyperlink does find its right target).

**Comment by jfbu** [comment]
As a hint to what is going on, I indicate that if one adds a `\global` to `\@xfootnote` like this
```latex
\makeatletter
\def\@xfootnote [#1]{\begingroup \global\csname c@\@mpfn \endcsname #1\relax \unrestored@protected@xdef \@thefnmark {\thempfn }\endgroup \@footnotemark \@footnotetext }%
\makeatother
```
the printed number is ok. But then the footnote counter gets offset which is bad.

(`\@xfootnote`  is not modified by hyperref, so I could try the above which only has the extra `\global` simply).

**Comment by jfbu** [comment]
Actually, this is initially an issue of longtable: it is not clear from longtable documentation that the `\footnote[N]{footnote text}` syntax is not allowed. ``hyperref`` does not change that.

**Comment by u-fischer** [comment]
It seems not to be an hyperref issue, so I'm closing here. Please move it to longtable if you think that there is a longtable issue.
