### ISSUE TITLE
Breaking links with `ocgcolorlinks` enabled.

### ISSUE THREAD

**Issue by Ps0ke** [ho-tex/hyperref#31]
As one of the maintainers [stated](http://tex.stackexchange.com/a/103796/21731), breaking links across lines is not possible with `ocgcolorlinks` enabled (hence being marked as *experimental*).
In [this tex.sx thread](http://tex.stackexchange.com/a/47309/21731) Ben Berner posted a workaround and mentioned that he tried to contact the maintainers, but never heard back.
Since it seems to work fine with pdfLaTeX (but I also don't know where it could lead to problems, no knowledge of TeX/PDF internals), I thought I'd post it here, in case you missed it. Feel free to close the issue, if this was settled long ago.
Note: it does not work with luaLaTeX (`\pdfpagewidth` not found)

**Comment by davidcarlisle** [comment]
thank you for the report, it is good to log issues here so they are
recorded even if there is not currently a lot of resources available to
implement extensions.

**Comment by u-fischer** [comment]
ocgcolorlinks have been reimplemented by the `ocgx2` package along the lines of Ben Lerner's patch, as stated in this answer https://tex.stackexchange.com/a/361453/2388. With 

       \usepackage{hyperref}
       \usepackage[ocgcolorlinks]{ocgx2}

one get links that can break across lines. So I don't see the need to add the package to hyperref, but a reference to the ocgx2 package in the readme.pdf would be good.

**Comment by ivankokan** [comment]
I would like to ask whether option `ocgcolorlinks` is still available for `hyperref` itself? If not, I suggest removing its mention from `README.xml`, and review the corresponding code within `hluatex.dtx`.

**Comment by u-fischer** [comment]
I added a reference to ocgx2 to the manual.
