### ISSUE TITLE
improve documentation of  PDF form parameters

### ISSUE THREAD

**Issue by donovaly** [ho-tex/hyperref#34]
While creating a PDF form I found out that the parameter _borderstyle_ can have the values
**U** (underlined), **S** (solid), **D** (dashed), **B** (bevel) or _I_ (inverted bevel)

But _borderstyle_ is not even mentioned in the hyperref manual.

I also found out that the settings
_color_
_borderstyle=B_
_borderstyle=I_
have no effect for popdown choice menus.

I assume that this is not a bug in hyperref but just not described, right? If so, could this information please be added to the manual that others don't have the same problems.

**Comment by davidcarlisle** [comment]
This is in fact the same is as #69, the documentation was in README.tex not in the manual, I have just moved the whole "new features" section to the main manual. in the change  2e62bb8
