### ISSUE TITLE
pdfstringdef bug

### ISSUE THREAD

**Issue by lstonys** [ho-tex/hyperref#35]
Hi, I found a bug ` \pdfstringdef` crash (I head some commands in \section).  
Message:
```
! Missing \endcsname inserted.
<to be read again>
\aaa
l.14 \pdfstringdef\foo{\mydef abc}
```

MWE:
```
\documentclass{article}
\usepackage{hyperref}

\makeatletter
\DeclareRobustCommand\mydef[1]{
  \def\aaa {ab}
  \@ifundefined{qq\aaa}{}{}
  }
\makeatother

\begin{document}
\pdfstringdef\foo{\mydef abc}
\end{document}
```

**Comment by davidcarlisle** [comment]
I'm not sure what you expect this to do `\pdfstringdef` is intended to specify simpler "safe" strings to use in pdf string contexts macros that make internal definitions like your `\mydef` are exactly the macros that typically one would need to _replace_ using `\pdfstringdef` not  use in the replacement text.  You would see similar errors if you use `\mydef`  in` \typeout` or a heading.

**Comment by lstonys** [comment]
Sorry for disturbing I expected that `\pdfstringdef` will skip this macro as unexpandable. My example was not correct. Macro was defined like `\DeclareRobustCommand\mydef[1]{...}` and it was expanded anyway.
 But rewriting it with `\protected\def` solved the problem:

> (hyperref)                removing `\mydef'

So I can fix that definition in my style.  
Thanks, Linas

**Comment by davidcarlisle** [comment]
ah, I can look what it's doing with \protect, thanks.

**Comment by davidcarlisle** [comment]
I think I'm going to close this with no action, while it would be possible to avoid the error by making commands declared robust to expand to nothing, it is unlikely to make a sensible string and as the only reason to use pdfstringdef is to manually provide "good" string replacements, this seems unnecessary extra complication in what is already complicated processing.
