### ISSUE TITLE
Hook for aditional \hyper@normalise defs

### ISSUE THREAD

**Issue by lstonys** [ho-tex/hyperref#36]
Hi, would be good to have a hook in` \hyper@normalise` where one could overwrite his own.
For example now `\texttildelow` does not work in `\href` (re-typesetting is not an option) . 

```
\documentclass{article}
\usepackage{textcomp}
\usepackage{hyperref}

\begin{document}
\href{http://www.tilde.com/\protect\texttildelow}{www.tilde.com/\protect\texttildelow}
\end{document}
```

Hook could be somewhere:
 ```
 \gdef\hyper@normalise{^^A
    \begingroup
    \catcode`\^^M\active
    \def^^M{ }^^A
    \catcode`\%\active
    \let%\@percentchar
    \let\%\@percentchar
    \catcode`\#\active
    \def#{\hyper@hash}^^A
    \def\#{\hyper@hash}^^A
    \@makeother\&^^A
    \edef&{\string&}^^A
    \edef\&{\string&}^^A
    \edef\textunderscore{\string_}^^A
    \let\_\textunderscore
    \catcode`\_\active
    \let_\textunderscore
    \let~\hyper@tilde
    \let\~\hyper@tilde
    \let\textasciitilde\hyper@tilde
    \let\\\@backslashchar
    \edef${\string$}^^A
    \Hy@safe@activestrue
    \csname hyper@normalise@hook\endcsname % <--HERE
    \hyper@n@rmalise
    }
```

**Comment by u-fischer** [comment]
I don't quite understand your example.  Why don't you use `\href{http://www.tilde.com/~}{www.tilde.com/\texttildelow}`  if you want the tilde be typeset differently? And which code for `\texttildelow` do you want to add with the new hook? `\let\texttildelow\hyper@tilde`  looks a bit pointless and more complicated setups will probably break the link.

**Comment by lstonys** [comment]
Such a typesetting just comes from authors f.e. "... Ph.D. thesis, Univ. Cambridge. Available at
\href{http://www.math.ubc.ca/~ben/}{http://www.math.ubc.ca/\texttildelow ben/}" and retypsetting is not an option.  And if one has other active characters in url (f.e. " :" in french typesetting is outputted with a small space) there would be a place to deactivate it.

**Comment by u-fischer** [comment]
Your example works fine without any hook and the colon doesn't give an additional space:

```

\documentclass{article}
\usepackage[french]{babel}
\usepackage{textcomp}
\usepackage{hyperref}
\begin{document}
\href{http://www.math.ubc.ca/~ben/}{http://www.math.ubc.ca/\texttildelow ben/}

\end{document}
```

![urlhook](https://user-images.githubusercontent.com/4047173/31068194-35933a60-a757-11e7-8323-9a10b3bf15fc.PNG)

**Comment by lstonys** [comment]
Indeed `\texttildelow` works now. But spacing is wrong before ":" in url.  And on the hook one could turn off french spacing. 

\documentclass{article}
\usepackage[french]{babel}
\usepackage{textcomp}
\usepackage{hyperref}
\begin{document}
text 20:20
\href{http://www.math.ubc.ca/~ben/}{http://www.math.ubc.ca/\texttildelow ben/20:20}
\end{document}

![hyper](https://user-images.githubusercontent.com/25791710/31069953-46538264-a767-11e7-9dbe-7f3539cb158a.png)

**Comment by u-fischer** [comment]
You seem to use xelatex or lualatex. There the handling of ":" is different. Redefining  ":" wouldn't work. 

But beside this: You are asking for a hook in the wrong place. Definitions in this place would affect the link (the "popup"), not the printed text. What you actually want is a hook to insert something (e.g. `\NoAutoSpacing`  in `\hyper@link@`

```
\documentclass{article}
\usepackage[ngerman,french]{babel}
\usepackage{textcomp,etoolbox}
\usepackage{hyperref}

\begin{document}

\href{xyabc}{a:b}

\href{xy:abc}{a:b}

\href{xyabc}{\NoAutoSpacing a:b}

\href{xy:abc}{\NoAutoSpacing a:b}

\makeatletter
\patchcmd{\hyper@link@}
   {\expandafter{\Hy@tempb}{#4}}
   {\expandafter{\Hy@tempb}{blblbl \NoAutoSpacing #4}}
   {}{\fail}
\makeatother

\href{xyabc}{a:b}

\href{xy:abc}{a:b}

\end{document}
```

![hookhyper](https://user-images.githubusercontent.com/4047173/31074360-905aebd2-a770-11e7-81a0-4f78af34f52e.PNG)

**Comment by lstonys** [comment]
`\texttildelow` don't work in TL2016 in `\href` first parameter (it crash with infinite recursion).  That's why I wanted to have a hook where I could do `\let\texttildelow\hyper@tilde`.  With TL2017 I don't get error, but `\texttildelow` seems as a text in hyperlink (pop up) and there is not tilde in url output et all. 

\patchcmd is more a dirty trick and not a permanent solution :) I think that empty hooks in certain places are useful for  other package programmers.

![hyper2](https://user-images.githubusercontent.com/25791710/31076613-bc1713aa-a783-11e7-8257-84c04536d171.png)

**Comment by u-fischer** [comment]
Sorry but using `\texttildelow` in the **first** argument of `\href` is wrong coding.  That you don't get an output is not a hyperref problem: Try it outside of \href and you will see. The font hasn't the glyph, so you should either change the font, or map `\texttildelow` e.g. with `\let\texttildelow\textasciitilde` to the normal tilde (which would solve your problem with the link too).

And regarding the patch: You can also redefine or patch `\hyphen@chars`. But the main point is that patching `\hyper@normalise` won't work, it won't do what you want.

**Comment by davidcarlisle** [comment]
I think given @u-fischer's analysis here I plan to close with no action.
