### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by kberry** [ho-tex/hyperref#4]
(import from https://puszcza.gnu.org.ua/bugs/index.php?265, author Xavier <somenxavier>)

The catalan translation is not provided. I send you the translation

\def\HyLang@catalan{%
\def\equationautorefname{Equaci\'o}%
\def\footnoteautorefname{Nota al peu de p\`{a}gina}%
\def\itemautorefname{Element}%
\def\figureautorefname{Figura}%
\def\tableautorefname{Taula}%
\def\partautorefname{Part}%
\def\appendixautorefname{Ap\`{e}ndix}%
\def\chapterautorefname{Cap\'itol}%
\def\sectionautorefname{Secci\'o}%
\def\subsectionautorefname{Subsecci\'o}%
\def\subsubsectionautorefname{Subsubsecci\'o}%
\def\paragraphautorefname{Par\`{a}graf}%
\def\subparagraphautorefname{Subpar\`{a}graf}%
\def\FancyVerbLineautorefname{L\'inia}%
\def\theoremautorefname{Teorema}%
\def\pageautorefname{P\`{a}gina}%

I hope see it in next release.

Reference: https://tex.stackexchange.com/questions/94509/make-hyperrefs-autoref-output-in-bulgarian

**Comment by somenxavier** [comment]
@davidcarlisle  It seems good to me. Thanks for fixed this issue

**Comment by somenxavier** [comment]
When this will be visible to public? When will you release new version with this fix?

**Comment by davidcarlisle** [comment]
@somenxavier not this week as @kberry  is finalising the texlive 2016 dvds _today_ and a big hyperref update today would be too scary, but as soon as texlive 2016 is done, I'll try to get this onto ctan so it would be in the first round of updates from tlmgr. Next week, probably.

**Comment by somenxavier** [comment]
No hurry. I will not need until september.

**Comment by davidcarlisle** [comment]
hyperref v6.83p uploaded to CTAN
