### ISSUE TITLE
No support for \and in \author (pdfusetitle)

### ISSUE THREAD

**Issue by tkalliom** [ho-tex/hyperref#44]
### What I attempted
```
\documentclass{article}

\usepackage[pdfusetitle]{hyperref}

\author{John Doe\and Jane Doe}
\title{A Paper}

\begin{document}
  \maketitle
\end{document}
```
### What I expected to happen
As `\and` is the standard way to separate multiple authors, I expected to see PDF metadata which separates the authors in a format commonly assigned the semantics of a list by software. (There seems to be no standard about this, AFAIK, ~~`exiftool` only parses `/Author(John Doe, Jane Doe)` while~~ Adobe produces `/Author(John Doe; Jane Doe)` but will recognize the former)

### What happened
The metadata produced was an unseparated string:

```
/Author(John DoeJaneDoe)
```

**Comment by tkalliom** [comment]
There is no LaTeX "standard" for inputting keywords, so I don't consider it a bug, but maybe the implementation of `\and` could also cover an implementation for keywords of `\and` (to be in line with LaTeX) or `\sep` (to be in line with the pdfx package)?

**Comment by davidcarlisle** [comment]
I can confirm, I suspect that the fix is to add a local setting of `\and` as in your modified file below.
I'll try to incorporate such a fix next time the package is updated (but I'm not sure when that will be)
```
\documentclass{article}

\usepackage[pdfusetitle]{hyperref}
\makeatletter
\def\Hy@UseMaketitleString#1{%
  \ltx@IfUndefined{Hy@#1}{}{%
    \begingroup
      \def\and{, }%<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      \let\Hy@saved@hook\pdfstringdefPreHook
      \pdfstringdefDisableCommands{%
        \expandafter\let\expandafter\\\csname Hy@newline@#1\endcsname
        \let\newline\\%
      }%
      \expandafter\ifx\csname @pdf#1\endcsname\@empty
        \expandafter\pdfstringdef\csname @pdf#1\endcsname{%
          \csname Hy@#1\endcsname\@empty
        }%
      \fi
      \global\let\pdfstringdefPreHook\Hy@saved@hook
    \endgroup
  }%
}
\makeatother

\author{John Doe\and Jane Doe}
\title{A Paper}

\begin{document}
  \maketitle
\end{document}
```

**Comment by davidcarlisle** [comment]
@tkalliom do you think it would be enough to always use a comma or does hyperref need yet another setting key to allow it to be a semicolon or any other user supplied string?

**Comment by tkalliom** [comment]
@davidcarlisle the metadata is as much for machines as it is for humans (think search indexing, filtering) so I think it should be in a fixed, semantic format. The separators that are most likely to be compatible and supported are `,` and `;`.

What Adobe does: I could not find any proper documentation or even sample PDFs with multiple authors with a quick search, but [this post](https://forums.adobe.com/message/5583110) would suggest they have a kind of “be conservative in what you produce and liberal in what you accept” approach: only produce PDFs with semicolons as a separator, but when reading PDFs, treat the field like a CSV row with either commas or semicolons as a separator (seems a bit of a mess).

What others do: exiftool does not interpret parse the author field as all, treating it as just a string. It does parse the keywords, however, but only on commas or spaces if there are no commas present. Pdfx has chosen semicolon-and-space as the separator in metadata lists.

If you want my opinion: just output `/Author(John Doe; Jane Doe)`. I can think of no case where that is worse than the current behavior, and if someone really wants to do something else, they can just set the `pdfauthor` manually as all co-authors have had to to until now. Implementing enquotation so `\author{John Doe, Jr.}` would produce `/Author("John Doe, Jr.")` would be nice, but that’s another issue and a lot more work for a niche than the low-hanging fruit of `\and` redefinition.

Of course, when there is no actual specification, it’s all up to the implementer to decide.

**Comment by davidcarlisle** [comment]
@tkalliom  thanks I'll probably just do as in the initial reply, but with ; at least for a first release.

(I'm just "looking after" hyperref while Heiko is busy elsewhere so I don't want to make deep changes
especially in code I don't know that well:-) 

It's tempting to try to do more parsing with the names, but as article class is so basic, and every journal class adds some different internals, trying to parse the internal saved author string is likely to be error prone, but just locally defining `\def\and{; }` must be pretty safe.

thanks for raising the issue (I'll leave open until i actually update the code)
