### ISSUE TITLE
Using dvips will lead to PDFs having XMP with broken character encoding

### ISSUE THREAD

**Issue by tkalliom** [ho-tex/hyperref#47]
When compiling a file into DVI and then further via `dvips`, the resulting file will have XMP metadata. In the metadata, non-ASCII Latin1 characters are broken into some three-byte sequences, while non-Latin1 characters (like Š in the example below) produce the correct UTF-8 byte sequence.

For the document
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\title{Non-AŠCIÍ} \newcommand{\keywords}{ümlauts, accénts}
\usepackage[unicode,pdfusetitle]{hyperref}\hypersetup{pdfkeywords=\keywords}
\begin{document}
Hello world
\end{document}
```
compiled with `etex -fmt=latex main.tex && dvips main.dvi && ps2pdf main.ps`, `exiftool` will report
```
Producer                        : dvips + GPL Ghostscript 9.20
Keywords                        : ￼mlauts, acc￩nts
Creator Tool                    : LaTeX with hyperref package
Format                          : application/pdf
Title                           : Non-AŠCIￍ
```

I’m not really sure whether this is a hyperref bug or if the fault lies somewhere else... The documentation does not mention XMP being produced, so if this is a “feature” of some other tool in the chain, a warning or some pointers might be in order.

**Comment by u-fischer** [comment]
On windows I see no problem. Title and keywords are correct in the document properties dialog e.g. of the adobe reader. In the command line the output of exiftool is correct if I switch the code page to unicode with `chcp 65001`. With the default code page I get 

~~~
Title                           : Non-A┼áCI├ì
Keywords                        : ├╝mlauts, acc├®nts
~~~

**Comment by tkalliom** [comment]
Huh, that’s odd. What’s your GhostScript version? I attached the PDF which I got; inspecting it with a hex editor will confirm that Š produced the correct UTF-8 sequence `0xC5 0xA0` while e.g. Í produced  `0xEF 0xBF 0x8C`

[main.pdf](https://github.com/ho-tex/hyperref/files/1422872/main.pdf)

**Comment by u-fischer** [comment]
I have ghostscript 9.22 from texlive 2017. If I use ps2pdf from a texlive 2016 with ghostscript 9.21  I get the wrong output for the Í too. With older ghostscript (9.19) it is ok again.

**Comment by tkalliom** [comment]
Okay, so since the fault lies in Ghostscript and they have already fixed it, this issue can probably be closed.
