### ISSUE TITLE
hyperlink to theorem begin with enumerate wrong

### ISSUE THREAD

**Issue by jiaopjie** [ho-tex/hyperref#48]
I use `amsthm` for theorems and `hyperref` for hyperlink. I have some theorem begin with enumerates. In this case, the hyperlink associated to the theorem is wrong.

```
\documentclass{article}
\usepackage{amsthm, hyperref}
\newtheorem{theorem}{Theorem}
\begin{document}
\autoref{thm:1}.
\autoref{thm:2},
\autoref{item:1}.
\clearpage
\begin{theorem}\label{thm:1}
  This is a test for theorem.
\end{theorem}
\clearpage
\begin{theorem}\label{thm:2}
  \begin{enumerate}
    \item\label{item:1} Item 1
    \item\label{item:2} Item 2
  \end{enumerate}
\end{theorem}
\end{document}
```
I found that the hyperlink `Theorem 1` and `item 1` work well, but `Theorem 2` seems have no target.

And, I get some warning `name{theorem 2} has been referenced but does not exist, replaced by a fixed one`.

So, is there something wrong, here?

**Comment by u-fischer** [comment]
Well it is wrong, after all the links don't work. But amsthm uses \everypar and so defers the typesetting, and lists also make quite an effort to start the typesetting only when the text is encountered. So the label is quite hanging in the air. Imho the only way to get the correct label is `\begin{theorem}\leavevmode\label{thm:2}`  (but this changes the layout).

**Comment by ilyaza** [comment]
I’m lost: why the `SPACE` after `\label` does not start the theorem?  At least 20 years ago I needed `%` after all the `\label`s to avoid spurious `SPACE`; did it change?

**Comment by u-fischer** [comment]
I would say that is a duplicate of https://github.com/ho-tex/hyperref/issues/8

**Comment by jiaopjie** [comment]
> I would say that is a duplicate of #8

Yes, I see it. Should I close this issue?
