### ISSUE TITLE
Greek language for \autoref

### ISSUE THREAD

**Issue by christosg88** [ho-tex/hyperref#52]
I would like to contribute the Greek translations for \autoref, since Greek is not supported currently, but I can't find the way. Could you point me to the place where the changes should be made, or the person I should contact?

**Comment by davidcarlisle** [comment]
Thanks for the offer.
For the actual translations you would just need to provide a definition  of `\HyLang@greek` equivalent to

```
\def\HyLang@english{%
  \def\equationautorefname{Equation}%
  \def\footnoteautorefname{footnote}%
  \def\itemautorefname{item}%
  \def\figureautorefname{Figure}%
  \def\tableautorefname{Table}%
  \def\partautorefname{Part}%
  \def\appendixautorefname{Appendix}%
  \def\chapterautorefname{chapter}%
  \def\sectionautorefname{section}%
  \def\subsectionautorefname{subsection}%
  \def\subsubsectionautorefname{subsubsection}%
  \def\paragraphautorefname{paragraph}%
  \def\subparagraphautorefname{subparagraph}%
  \def\FancyVerbLineautorefname{line}%
  \def\theoremautorefname{Theorem}%
  \def\pageautorefname{page}%
}

```

preferably using the ascii \textalpa, \textbeta... markup (but a more readable version using UTF-8 greek would be fine as well we could mechanically convert here, given the translations. see the definition for russian in hyperref.dtx which starts at

https://github.com/ho-tex/hyperref/blob/master/hyperref.dtx#L5780

Due to encoding issues it might in the end be better for these definitions to live with babel, but if you could supply the translations we could experiment with best place to make them fit.

The main maintainer of hyperref is currently inactive due to other commitments so we are acting in a caretaker role to fix any serious bugs but I don't have a lot of time for hyperref maintenance unfortunately, however if you could add translations of the above to this issue that would already help (anyone needing this now could define those commands in their preamble until a real `greek` option is implemented.)

**Comment by christosg88** [comment]
Here is a UTF-8 version. Note that the translation for "Table" in nominative is "Πίνακας" but when you refer to it, the accusative case is generally used, so it becomes "Πίνακα". All other translation remain unchanged.
```TeX
\def\HyLang@greek{%
    \def\equationautorefname{Εξίσωση}%
    \def\footnoteautorefname{υποσημείωση}%
    \def\itemautorefname{στοιχείο}%
    \def\figureautorefname{Σχήμα}%
    \def\tableautorefname{Πίνακα}%
    \def\partautorefname{Μέρος}%
    \def\appendixautorefname{Παράρτημα}%
    \def\chapterautorefname{κεφάλαιο}%
    \def\sectionautorefname{ενότητα}%
    \def\subsectionautorefname{υποενότητα}%
    \def\subsubsectionautorefname{υπο-υποενότητα}%
    \def\paragraphautorefname{παράγραφος}%
    \def\subparagraphautorefname{υποπαράγραφος}%
    \def\FancyVerbLineautorefname{γραμμή}%
    \def\theoremautorefname{Θεώρημα}%
    \def\pageautorefname{σελίδα}%
}
```

I tried to convert the ASCII markup, but couldn't figure out how to use accents with them. If you know let me know and I'll finish it. Here is the **incomplete** version. Note that ά, έ, ή, ί, ό, ώ are needed.

```TeX
\def\HyLang@greek{%
    \def\equationautorefname{\textEpsilon\textxiί\textsigma\textomega\textsigma\texteta}%
    \def\footnoteautorefname{\textupsilon\textpi\textomikron\textsigma\texteta\textmugreek\textepsilonί\textomega\textsigma\texteta}%
    \def\itemautorefname{\textalpha\textnu\texttau\textiota\textkappa\textepsilonί\textmugreek\textepsilon\textnu\textomikron}%
    \def\figureautorefname{\textSigma\textchiή\textmugreek\textalpha}%
    \def\tableautorefname{\textPiί\textnu\textalpha\textkappa\textalpha}%
    \def\partautorefname{\textMuέ\textrho\textomikron\textvarsigma}%
    \def\appendixautorefname{\textPi\textalpha\textrhoά\textrho\texttau\texteta\textmugreek\textalpha}%
    \def\chapterautorefname{\textkappa\textepsilon\textphiά\textlambda\textalpha\textiota\textomikron}%
    \def\sectionautorefname{\textepsilon\textnuό\texttau\texteta\texttau\textalpha}%
    \def\subsectionautorefname{\textupsilon\textpi\textomikron\textepsilon\textnuό\texttau\texteta\texttau\textalpha}%
    \def\subsubsectionautorefname{\textupsilon\textpi\textomikron\textupsilon\textpi\textomikron\textepsilon\textnuό\texttau\texteta\texttau\textalpha}%
    \def\paragraphautorefname{\textpi\textalpha\textrhoά\textgamma\textrho\textalpha\textphi\textomikron\textvarsigma}%
    \def\subparagraphautorefname{\textupsilon\textpi\textomikron\textpi\textalpha\textrhoά\textgamma\textrho\textalpha\textphi\textomikron\textvarsigma}%
    \def\FancyVerbLineautorefname{\textgamma\textrho\textalpha\textmugreek\textmugreekή}%
    \def\theoremautorefname{\textTheta\textepsilonώ\textrho\texteta\textmugreek\textalpha}%
    \def\pageautorefname{\textsigma\textepsilon\textlambdaί\textdelta\textalpha}%
}
```

**Comment by davidcarlisle** [comment]
Thanks I was going to make a small test file but now it seems I am confused, sorry for my google translate Greek but I made
```

\documentclass{article}
\usepackage[T1,LGR]{fontenc}
\usepackage[greek]{babel}
\usepackage[utf8]{inputenc}

\usepackage{hyperref}

\begin{document}
\section{Κάτι}
\label{sec:here}

\begin{figure}
\caption{\label{fig:here} Γειά σου Κόσμε}
\end{figure}

\autoref{sec:here}

\autoref{fig:here}
\end{document}
```


But babel seems to have already translated the autoref strings (with different translation I think):

I get 

![image](https://user-images.githubusercontent.com/1268738/34827881-866eb77c-f6d3-11e7-8ced-2f4c1d3254f1.png)

I was expecting to get a message from

     \errmessage{No definitions for language greek' found!}%


As I can't read the input or the result it's a bit hard for me to be sure if the current output is at all sensible. Is it what you expected to see?

**Comment by davidcarlisle** [comment]
Ah I think the current "Greek" in the autoref output isn't really a translation just the english words "transliterated" by the LGR. So quite probably nonsense. OK I'll try to make a test of incorporating your translations (possibly not today)

**Comment by eg9** [comment]
Just for information: a letter with *tonos* is obtained by prefixing its name with `\acctonos`, so `\acctonos\texteta` and similar should work.

**Comment by davidcarlisle** [comment]
Until hyperref is extended, I think this makes it use your translations

```

\documentclass{article}
\usepackage[T1,LGR]{fontenc}
\usepackage[greek]{babel}
\usepackage[utf8]{inputenc}

\makeatletter
\def\HyLang@greek{%
    \def\equationautorefname{Εξίσωση}%
    \def\footnoteautorefname{υποσημείωση}%
    \def\itemautorefname{στοιχείο}%
    \def\figureautorefname{Σχήμα}%
    \def\tableautorefname{Πίνακα}%
    \def\partautorefname{Μέρος}%
    \def\appendixautorefname{Παράρτημα}%
    \def\chapterautorefname{κεφάλαιο}%
    \def\sectionautorefname{ενότητα}%
    \def\subsectionautorefname{υποενότητα}%
    \def\subsubsectionautorefname{υπο-υποενότητα}%
    \def\paragraphautorefname{παράγραφος}%
    \def\subparagraphautorefname{υποπαράγραφος}%
    \def\FancyVerbLineautorefname{γραμμή}%
    \def\theoremautorefname{Θεώρημα}%
    \def\pageautorefname{σελίδα}%
}
\g@addto@macro\extrasgreek\HyLang@greek
\makeatother

\usepackage{hyperref}



\begin{document}
\section{Κάτι}
\label{sec:here}

\begin{figure}
\caption{\label{fig:here} Γειά σου Κόσμε}
\end{figure}

\autoref{sec:here}

\autoref{fig:here}
\end{document}

```

**Comment by davidcarlisle** [comment]
@christosg88  @eg9  thanks for your help.

With the checkin I just made I think this test file works as you would want

```

\documentclass{article}
\usepackage[T1,LGR]{fontenc}
\usepackage[greek]{babel}
\usepackage[utf8]{inputenc}


\usepackage[]{hyperref}



\begin{document}
\section{Κάτι}
\label{sec:here}

\begin{figure}
\caption{\label{fig:here} Γειά σου Κόσμε}
\end{figure}

\autoref{sec:here}

\autoref{fig:here}
\end{document}
```

Note that you need the  `[unicode]` option to get good bookmarks 

![grtest](https://user-images.githubusercontent.com/1268738/38214794-9e38012c-36bd-11e8-8e2c-f8bb1a61c2e0.png)
