### ISSUE TITLE
Include information about NoHyper in the documentation

### ISSUE THREAD

**Issue by Leandriis** [ho-tex/hyperref#55]
There are quite some questions concerning the temporary disabling of hyperlinks using the hyperref package (e.g. https://tex.stackexchange.com/q/116338/134144, https://tex.stackexchange.com/q/118182/134144, https://tex.stackexchange.com/q/6093/134144, https://tex.stackexchange.com/q/415625/134144) where using the `NoHyper` environment comes in handy. 

Looking throught the documentation I could unfortunately not find any information on this useful environment, so it might be worth adding some explanation to help users find out about it.

**Comment by davidcarlisle** [comment]
yes will see what I can do, it is documented in hyperref.pdf

texdoc hyperref.pdf

section 23

% \section{Localized nullifying of package}
% Sometimes we just don't want the wretched package interfering
% with us....

but it doesn't seem to be mentioned in the separate manual, which is whet
most users see as that's what is returned by

texdoc hyperref

**Comment by Leandriis** [comment]
Thank you for your immediate reply. 
I must admit that I have been searching in manual.pdf that is available at ctan. Until now I did not know about the different content in hyperref.pdf.
