### ISSUE TITLE
hyperref: possible bug when using \@addtoreset {<counter>}{@ckpt}

### ISSUE THREAD

**Issue by FOCCOF** [ho-tex/hyperref#56]
Hello,

The LaTeX macro \cl@@ckpt maintains a list of counter. 
The simplest way to append a counter in the list is to use :
\@addtoreset {counter}{@ckpt}

But hyperref redefines \@addtoreset in order for it to define
    \theH<counter>
without the longer test made when the command \theH<counter>
does not exist: if \theH<counter> does not exist, hyperref
executes \HyCnt@ProvideTheHCounter which looks into \cl@@ckpt
to find a possibly parent counter.

But @ckpt is NOT a counter, and \cl@@ckpt is NOT comparable
to \cl@section for example.

So:
     \@addtoreset {counter}{@ckpt}

has not the same meaning as :
     \@addtoreset {counter}{parent-counter}

But hyperref does not make the check, so that:
     \@addtoreset {counter}{@ckpt}

finally defines: \theHcounter -> \the@clckpt .\the\value {counter}

And \the@ckpt is a undefined control sequence, since @ckpt is not a counter.

I think hyperref should check that special use of \@addtoreset with @ckpt, when redefining \@addtoreset. 

Minimal example that shows the problem :
%------------------------------------------------------------
\documentclass [a4paper]{article}
\usepackage [T1]{fontenc}
\usepackage [utf8]{inputenc}
\usepackage {hyperref}

\makeatletter
\newcount \c@mycount
\@addtoreset {mycount}{@ckpt}

\begin{document}

meaning of theHmycount = \meaning\theHmycount

\end{document}
% ----------------------------------------------------------

**Comment by davidcarlisle** [comment]
Hmm Thanks for the report, hyperref could probably add a guard here but I
think the input document is in error

\newcount \c@mycount
\@addtoreset {mycount}{@ckpt <https://github.com/ckpt>}

isn't really a supported way to declare a latex counter and (as seen here)
doesn't set up everything that is assumed to be declared for a latex
counter.
Other things could fail here not just hyperref

replacing those two lines by

\newcounter{mycount}

results in \theHmycount being defined to \arabic{mycount}

Is there any reason why \newcounter can't be used in your actual use case?

**Comment by FOCCOF** [comment]
No, there is no real reason. Obviously, in LaTeX syntax, \newcounter does the trick.

I'm used to write for both plain TeX and LaTeX, so something like :

\ifdefined\newcounter \newcounter {mycount}
\else                              \newcount \c@mycount \fi

does the job. plain TeX does not maintain a list of counter as far as i know...

Nevertheless, \numberwithin [option]{counter}{parent-counter} tests if <counter> AND <parent-counter> exist (ie if \c@counter and \c@parent-counter are defined)

While defining \theHcounter, hyperref should perform the same test : there is no point to introduce a control sequence like "\theHparent-counter" if \c@parent-counter is undefined... in my opinion.

Best regards.

PS: i wonder why my posts about hyperref turned on / turned off have been deleted...

**Comment by davidcarlisle** [comment]
the plain tex you show does not do the full job as you show, a latex counter is not just a primitive count register whose name starts c@ it is a data structure including the register, print formats, reset lists etc. If you fake its initialisation then you need to fake the entire structure. It is not reasonable to expect every latex package that is using a counter to check that the counter has been incorrectly initialised. If the counter is declared using latex commands and is incorrectly initialised, that would be a latex kernel bug to be fixed there.

> PS: i wonder why my posts about hyperref turned on / turned off have been deleted...
As I thought I explained in the comment on those posts that is a known feature, that you may need to delete the aux file when adding or removing a package. This doesn't just apply to hyperref.

**Comment by josephwright** [comment]
@FOCCOF  Your other issue hasn't been deleted (which isn't I think actually possible), it's been closed. As @davidcarlisle  notes, this is well-known behaviour and will occur for anything that changes the nature of data written to the `.aux`.

**Comment by FOCCOF** [comment]
@josephwright O.K. But I thought Heiko Oberdiek provides commands such as \oldnewlabel and \newlabelxx in the .aux file in order to be able to switch hyperref on/off without failure...

**Comment by davidcarlisle** [comment]
you can catch some cases but it is hard to catch them all and certainly the
issue has been known about since the first drafts of the package, which is
why I closed those issues, as the behaviour is "expected" even if not
necessarily desirable.

**Comment by davidcarlisle** [comment]
I think on balance I'll close this as not supported as hyperref can't really catch non latex initialisations of  internal latex data structures.
