### ISSUE TITLE
Problem with labels when hyperref is turn on

### ISSUE THREAD

**Issue by FOCCOF** [ho-tex/hyperref#57]
I have not investigated much, but just try the following example :
 - First compile without \usepackage {hyperref}
 - Then compile with \usepackage {hyperref}

An error occurs in the second compilation: "Paragraph ended before \Hy@setref@link was complete"

\documentclass [a4paper]{article}
\usepackage [T1]{fontenc}
\usepackage [utf8]{inputenc}
%\usepackage [verbose]{hyperref}

% --------------------------------------------
\begin{document}

\section {One\label {One}}
\vskip5cm

Reference to \ref{One}.

\end{document}
% ---------------------------------------------

**Comment by davidcarlisle** [comment]
Please see the comments in issue #58, you need to delete the auxiliary files if adding or removing hyperref.
