### ISSUE TITLE
Problem with labels when hyperref is turned off

### ISSUE THREAD

**Issue by FOCCOF** [ho-tex/hyperref#58]
Hello again,

I've not investigated much, but a problem appears when :
    - \usepackage {hyperref}  is used -> first compilation
    - \usepackage {hyperref} is commented -> second compilation

At the second compilation (with \usepackage {hyperref} commented)
the \ref {One} is typeset as:  "1Onesection.1"

% -----------------------------------------------------------------------------
\documentclass [a4paper]{article}
\usepackage [T1]{fontenc}
\usepackage [utf8]{inputenc}
\usepackage [verbose]{hyperref}% < First compile with it, then comment this line for a second run >

\begin{document}

\section {One\label {One}}
\vskip5cm
Reference to \ref{One}.

\end{document}
%----------------------------------------------------------------------------------

**Comment by davidcarlisle** [comment]
That has always been an issue with hyperref (and many other packages such as babel or longtable etc that write to the aux file) If data is written to the aux file, then a package is removed the aux file is essentially corrupted and you may have to delete the aux file and allow a new one to be generated on the next run. In the case of hyperref you can also get the same type of error if you add hyperref to an existing document as it changes the structure of teh cross reference data that is written.

**Comment by shiny-eel** [comment]
Thanks @davidcarlisle ! This is another tedious issue that I came across, and your solution worked perfectly.
