### ISSUE TITLE
checked checkboxes and default radiobuttons

### ISSUE THREAD

**Issue by kberry** [ho-tex/hyperref#6]
(reposted from https://puszcza.gnu.org.ua/bugs/index.php?203, author A. van der Lee <vdlee>)

Hi all,

I have two similar problems, one with checkboxes and the other with radiobuttons:

Checkbuttons:

\documentclass{minimal}
\usepackage{hyperref}
\begin{document}
\begin{Form}
\CheckBox[checked,name=ch1]{Yes}
\end{Form}
\end{document}

This does not give a checked checkbox with a number of versions of Acrobat Reader. Reader 9 works, but not 10 and 11, nor Adobe Professional 10. It appears that such a problem was reported in 2005, but with Reader 5,6.

The other example, with radiobuttons tries to define a checked radiobutton for the second button.

\documentclass{article}
\listfiles
\usepackage[pdftex]{hyperref}
\begin{document}
\begin{Form}
\ChoiceMenu[radio,default=no,name=yesno]{Yes or no:}{Yes=yes,No=no}
\end{Form}
\end{document}

Setting default=yes works. I have not seen differences for different versions of Adobe Reader.
The problem is similar as for the one reported yesterday by Thorsten for choicemenus.

pdfTeX, Version 3.1415926-2.5-1.40.14 (MiKTeX 2.9)
Package: hyperref 2012/11/06 v6.83m Hypertext links for LaTeX

best wishes, Arie

**Comment by u-fischer** [comment]
Imho in the case of the checkbox the code of hyperref (I looked only at hpdftex.def!) is missing the Appearance Dictionary entry which tells the pdf viewer which value is the "on"-value:

```
\documentclass{article}

\usepackage{hyperref}
\makeatletter

\def\PDFForm@Check{%
  /Subtype/Widget%
  \Fld@annotflags
  \Fld@pageobjref
  \Fld@annotnames
  /FT/Btn%
  \Fld@flags
  /Q \Fld@align
  /BS<</W \Fld@borderwidth /S/\Fld@borderstyle>>%
  /AP<< /N <</Yes<<>>>> >>  %new string /Yes is from below
  /MK<<%
    \ifnum\Fld@rotation=\z@
    \else
      /R \Fld@rotation
    \fi
    \ifx\Fld@bordercolor\relax
    \else
      /BC[\Fld@bordercolor]%
    \fi
    \ifx\Fld@bcolor\relax
    \else
      /BG[\Fld@bcolor]%
    \fi
    /CA(\Hy@escapestring{\Fld@cbsymbol})%
  >>%
  /DA(/ZaDb \strip@pt\Fld@charsize\space Tf%
      \ifx\Fld@color\@empty\else\space\Fld@color\fi)%
  /H/P%
  \ifFld@checked /V/Yes/AS/Yes/AA <<>> \else /V/Off/AS/Off\fi
  \Fld@additionalactions  
}

\makeatother
\begin{document}
\begin{Form}
\CheckBox[checked=true,name=ch1]{Yes}
\end{Form}
\end{document}
```

![checkbox](https://cloud.githubusercontent.com/assets/4047173/15467553/71522a98-20df-11e6-9d13-ad01bb033888.PNG)

**Comment by u-fischer** [comment]
Regarding the radio buttons the problem is imho that *if* there is a default value one must make sure either that this value is used by all fields or that the non-defaults-buttons don't set a value. The buttons form a pair (they share the same field name), and if the first button gets a value like "off" it will force it upon the second which will now ignore its default value. 

```
\documentclass{article}
\usepackage{hyperref}

\makeatletter
%from driver: hpdftex.def
\def\PDFForm@Radio{%
  /Subtype/Widget%
  \Fld@annotflags
  \Fld@pageobjref
  \Fld@annotnames
  /FT/Btn%
  \Fld@flags
  /H/P%
  /BS<</W \Fld@borderwidth/S/\Fld@borderstyle>>%
  /MK<<%
    \ifnum\Fld@rotation=\z@
    \else
      /R \Fld@rotation
    \fi
    \ifx\Fld@bordercolor\relax
    \else
      /BC[\Fld@bordercolor]%
    \fi
    \ifx\Fld@bcolor\relax
    \else
      /BG[\Fld@bcolor]%
    \fi
    /CA(\Hy@escapestring{\Fld@radiosymbol})%
  >>%
  /DA(/ZaDb \strip@pt\Fld@charsize\space Tf%
      \ifx\Fld@color\@empty\else\space\Fld@color\fi)%
%  \ifx\@currValue\Fld@default %old code
%    /V/\Fld@default
%    /DV/\Fld@default
%  \else
%    /V/Off%
%    /DV/Off%
%  \fi
  \ifx\Fld@default\@empty %new code, the default value is used for all buttons
    /V/Off%
    /DV/Off%
  \else
   /V/\Fld@default
   /DV/\Fld@default
  \fi
  \Fld@additionalactions
}
\makeatother

\begin{document}
\begin{Form}

\ChoiceMenu[radio,default=yes,name=hyperrefA]{Yes or no:}{No=no,Yes=yes}

\ChoiceMenu[radio,default=no ,name=hyperrefB]{Yes or no:}{No=no,Yes=yes}

\ChoiceMenu[radio,            name=hyperrefC]{Yes or no:}{No=no,Yes=yes}

\end{Form}
\end{document}
```

![radiobuttons](https://cloud.githubusercontent.com/assets/4047173/15472396/3709b1aa-20fb-11e6-8b3d-59b145f99912.PNG)

**Comment by vdlee** [comment]
Dear Ulrike,

I think that you have found the proper solution for the two problems. Thanks a lot!

**Comment by davidcarlisle** [comment]
hyperref v6.83p uploaded to CTAN
