### ISSUE TITLE
Special characters treatment in hyperref

### ISSUE THREAD

**Issue by borisveytsman** [ho-tex/hyperref#60]
The following url `https://dx.doi.org/10.1002/(SICI)1097-0312(199610)49:10<1081::AID-CPA3>3.0.CO;2-A`, when used inside `\url` command, leads to the following link:  `https://dx.doi.org/10.1002/%28SICI%291097-0312%28199610%2949:10%3C1081::AID-CPA3%3E3.0.CO%3b2-A`, which is not valid

**Comment by davidcarlisle** [comment]
On 8 April 2018 at 22:34, Boris Veytsman <notifications@github.com> wrote:

> The following url https://dx.doi.org/10.1002/(SICI)1097-0312(199610)49:10<
> 1081::AID-CPA3>3.0.CO;2-A, when used inside \url command, leads to the
> following link: https://dx.doi.org/10.1002/%28SICI%291097-0312%28199610%
> 2949:10%3C1081::AID-CPA3%3E3.0.CO%3b2-A, which is not valid
>
> —
>
It looks OK, which part is not valid? ( is %23 ) is %29  < is %3C and > is
%3E ; is %3b

David

**Comment by borisveytsman** [comment]
When I click on the first link, it leads me to a paper by Nicola Garofalo and  Duy‐Minh Nhieu.  When I click on the second link, I get `This page isn’t working`

**Comment by davidcarlisle** [comment]
I just tried both of the links on your mail (using firefox) and both go to
the same place

**Comment by borisveytsman** [comment]
Hmmm.  Might be issue with a browser?  Should I file a bug with Google about Chrome?

**Comment by davidcarlisle** [comment]
I'm going to close as works-for-me, If you can find another example please re-open.
