### ISSUE TITLE
Warning when hyperref used with amsart and biblatex

### ISSUE THREAD

**Issue by ed359** [ho-tex/hyperref#61]
The following document compiles with a warning:
```latex
\documentclass{amsart}
\usepackage{biblatex}
\usepackage{hyperref}
\listfiles
\begin{document}
\end{document}
```
The warning is:
```
Package biblatex Warning: Patching footnotes failed.
(biblatex)                Footnote detection will not work.
```

Changing `amsart` to `article` kills the warning. Also, disabling hyperlinked footnotes by either (a) removing `hyperref` or (b) adding `[hyperfootnotes=false]` kills the warning. 

Edited information from `\listfiles`:
pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018)
amsart.cls    2017/10/31 v2.20.4
biblatex.sty    2018/03/04 v3.11 programmable bibliographies (PK/MW)
hyperref.sty    2018/02/06 v6.86b Hypertext links for LaTeX

The problem is probably something to do with how `amsart.cls` redefines `\@footnotetext`:
```latex
\long\def\@footnotetext#1{%
  \insert\footins{%
    \normalfont\footnotesize
    \interlinepenalty\interfootnotelinepenalty
    \splittopskip\footnotesep \splitmaxdepth \dp\strutbox
    \floatingpenalty\@MM \hsize\columnwidth
    \@parboxrestore \parindent\normalparindent \sloppy
    \protected@edef\@currentlabel{%
      \csname p@footnote\endcsname\@thefnmark}%
    \@makefntext{%
      \rule\z@\footnotesep\ignorespaces#1\unskip\strut\par}}}
```

Also filed on `biblatex` github: https://github.com/plk/biblatex/issues/744

**Comment by moewew** [comment]
This was also reported at the `biblatex` bug tracker and fixed there https://github.com/plk/biblatex/issues/744. There is nothing to do on the `hyperref` side (and it never really was a `hyperref` issue in the first place), so this issue can probably be closed.

**Comment by davidcarlisle** [comment]
@moewew  thanks I like this sort of issue!
