### ISSUE TITLE
frenchlinks option fails with fake small-caps

### ISSUE THREAD

**Issue by PhelypeOleinik** [ho-tex/hyperref#64]
In the comments to [this thread](https://tex.stackexchange.com/a/438365/134574), it was noticed that the following code throws a warning:

```latex
\documentclass{article}
\usepackage[garamond]{mathdesign}
\usepackage[frenchlinks]{hyperref}
\begin{document}
\section{test}\label{sec:test}
See~\ref{sec:test}
\end{document}
```

and, consequently, fails to typeset the link with small capitals.

The `frenchlinks` option does:

```latex
\def\Hy@colorlink#1{\begingroup\fontshape{sc}\selectfont}%
```

requesting a font shape named `sc`, but the Garamond font from `mathdesign` does not use `sc`, but `fsc` for "fake small capitals", thus the warning.

I think an improvement would be to use, instead:

```latex
\def\Hy@colorlink#1{\begingroup\fontshape{\scdefault}\selectfont}%
```

**Comment by davidcarlisle** [comment]
seems reasonable although another place that could be fixed would be of the
font package supplied a substitution from fsc to sc in the case that it is
not defining an sc variant so that would catch other non-hyperref cases
. (although hyperref could make your suggested change anyway)
