### ISSUE TITLE
`pdfusetitle` is not documented in the manual

### ISSUE THREAD

**Issue by ilyapopov** [ho-tex/hyperref#69]

**Comment by davidcarlisle** [comment]
er, yes, more generally it isn't clear why some things are documented in `README.tex` rather than the manual, in this case README has
```

\subsection{Option pdfusetitle}
\begin{verbatim}
 If option pdfusetitle is set then hyperref tries to
  derive the values for pdftitle and pdfauthor from
  \title and \author. An optional argument for \title and
  \author is supported (class amsart).
\end{verbatim}

```

I'll leave this open and try to  incorporate more of README.tex into the main manual before the next release.

Thanks for the report.

**Comment by davidcarlisle** [comment]
Almost all of README now moved to the manual , and the remaining parts are now just README.md markdown and no longer as xml/tex/pdf. Thanks for the report.
