### ISSUE TITLE
patch needed for \addcontentsline

### ISSUE THREAD

**Issue by FrankMittelbach** [ho-tex/hyperref#70]
Thus it would also need patching, eg

```
\usepackage{etoolbox}
\makeatletter
\patchcmd\addcontentsline
    {{\thepage}{\@currentHref}}
    {{\thepage}{\@currentHref}\protected@file@percent}
    {\typeout{patched}}
    {\typeout{patch failed}}
\makeatother
```
@davidcarlisle is that doable (easily?)

maybe with a guard for older kernels that don't know the command

_Originally posted by @FrankMittelbach in https://github.com/latex3/latex2e/issues/73#issuecomment-425101683_

**Comment by davidcarlisle** [comment]
@FrankMittelbach do you think I need to duplicate the definition or (rather easier to maintain in the code) just have `\ProvideCommand\protected@file@percent{something}` where _something_ could be a empty (or perhaps a catcode 12 % ?

**Comment by FrankMittelbach** [comment]
`\ProvideCommand\protected@file@percent{}` in my opinion

**Comment by davidcarlisle** [comment]
@FrankMittelbach  oh yes, I did see that discussion:-)

**Comment by davidcarlisle** [comment]
```
! Undefined control sequence.
l.8117 \ProvideCommand
```

Hmmm,
