### ISSUE TITLE
Micro-defects in documentation

### ISSUE THREAD

**Issue by ilyaza** [ho-tex/hyperref#72]
(A) Section 4: `|` leaks in 4 places (search for `|`)

(B) Section 4 says: “**The special characters `#` and `~` do not need to be escaped in any way.**”

It is not clear why `#` and `~` are so special; I would think that `_` and `%` are much more widely used.  Moreover, the statement above is **absolutely wrong**.  These characters **do** need to be escaped in most situations (such as footnotes etc.)

**Comment by dbitouze** [comment]
>It is not clear why # and ~ are so special;

I guess in the sense they are [reserved ones](https://latexref.xyz/dev/latex2e.html#Reserved-characters).

>These characters do need to be escaped in most situations (such as footnotes etc.)

I guess, it is meant they do not need to be escaped *in the URL*:

```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\href{https://latexref.xyz/dev/latex2e.html#Reserved-characters}{Reserved characters}

\href{https://www-cs-faculty.stanford.edu/~knuth/}{Donald's home page}
\end{document}
```

**Comment by ilyaza** [comment]
> > It is not clear why # and ~ are so special;
>
> I guess in the sense they are [reserved ones](https://latexref.xyz/dev/latex2e.html#Reserved-characters).

Did you try to follow this link?  There are 10 reserved chars, and (as I said) 2 more of them have a stronger chance to appear in URLs.

> > These characters do need to be escaped in most situations (such as footnotes etc.)
>
> I guess, it is meant they do not need to be escaped _in the URL_:

As I said, they **do** need to be escaped.
```
\documentclass{article}
\usepackage{hyperref}
\begin{document}

Some characters have special catcodes.%
		\footnote{See \href{https://latexref.xyz/dev/latex2e.html#Reserved-characters}{Reserved characters.}}

\end{document}
```

**Comment by u-fischer** [comment]
It is standard behaviour of all verbatim like commands that they don't work inside the arguments of other commands, but I added a few words about it and corrected the |.
