### ISSUE TITLE
Remove warning about xdvipdfmx producer

### ISSUE THREAD

**Issue by michael-o** [ho-tex/hyperref#76]
Based on https://sourceforge.net/p/xetex/bugs/93/. I can happily set {{pdfproducer}} with XeLaTeX and `xdvipdfmx`.

Can we drop this warning from `hyperref.dtx` for at least XeTeX?

Using:
XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX)
kpathsea version 6.3.0
Copyright 2018 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 61.1; using 61.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.1; using 2.9.1
Compiled with Graphite2 version 1.3.11; using 1.3.11
Compiled with HarfBuzz version 1.7.6; using 1.7.6
Compiled with libpng version 1.6.34; using 1.6.34
Compiled with poppler version 0.64.0
Compiled with fontconfig version 2.13.0; using 2.13.0

**Comment by michael-o** [comment]
The message in question is:


Package hyperref Warning: pdfproducer: xdvipdfmx will use its own setting
(hyperref)                instead of the value given on input line 29.

**Comment by u-fischer** [comment]
This will be resolved with the next update.
