### ISSUE TITLE
thanks breaks pdfusetitle

### ISSUE THREAD

**Issue by oliviercailloux** [ho-tex/hyperref#81]
As explained [here](https://tex.stackexchange.com/questions/466229/hyperref-option-pdfusetitle-with-thanks), hyperref with option `pdfusetitle` does not like `\title{The title\thanks{Thanks}}`: the title metadata becomes `The titleThanks`. 

I think it should be `The title`, thus the title metadata should not include the `\thanks` part.

**Comment by u-fischer** [comment]
It is no a bug that `\thanks` is not deactivated in "pdf" locations like the bookmarks or the metadata by default: hyperref can't disable every imaginable problematic command, the list would get too long.
I don't think that `\thanks` is used often enough in titles to justify its addition in the default list.

As a user you can always deactivate it with  `\pdfstringdefDisableCommands` in your document, or you can locally disable or replace it with `\texorpdfstring`.

**Comment by oliviercailloux** [comment]
If I dare insist, I understand that `hyperref` can’t imagine every possible intricate use of the `\title`, but this one does not seem intricate at all.

`\thanks` is used for nothing else than this kind of usage in the cover page; and this example use is given by no other than Leslie Lamport.

Perhaps the list of problematic command taken care of by `hyperref` could be limited to the ones given as examples in very famous books about LaTeX such as Lamport’s one? I believe that will not make such a huge list.

**Comment by u-fischer** [comment]
I think one can add it too `\Hy@UseMaketitleString`. This looks like the logical place - it will only be used together with pdfusetitle and so not polute the default list. 

~~~~
\documentclass{article}

\usepackage[pdfusetitle]{hyperref}

\makeatletter
\def\Hy@UseMaketitleString#1{%
  \ltx@IfUndefined{Hy@#1}{}{%
    \begingroup
      \let\Hy@saved@hook\pdfstringdefPreHook
      \pdfstringdefDisableCommands{%
        \expandafter\let\expandafter\\\csname Hy@newline@#1\endcsname
        \let\newline\\%
        \def\and{; }%
        \let\thanks\@gobble%<---new
      }%
      \expandafter\ifx\csname @pdf#1\endcsname\@empty
        \expandafter\pdfstringdef\csname @pdf#1\endcsname{%
          \csname Hy@#1\endcsname\@empty
        }%
      \fi
      \global\let\pdfstringdefPreHook\Hy@saved@hook
    \endgroup
  }%
}
\begin{document}
\title{The title\thanks{Thanks}} 

\maketitle
Hello.
\end{document}
~~~~

@davidcarlisle  any objection?

**Comment by u-fischer** [comment]
This will be resolved in the next hyperref version.
