### ISSUE TITLE
README seems wrongly or not hyperlinked on page 1 of file hyperref.pdf

### ISSUE THREAD

**Issue by jfbu** [ho-tex/hyperref#83]
Doing `texdoc hyperref` which opens `manual.pdf` then opening up the "Hyperref manual" bookmark to reveal "Sources: hyperref.dtx" and finally clicking on that one ends up with file `hyperref.pdf`. There the title page has links to various files. At my locale clicking on README does nothing.

![capture d ecran 2019-01-08 a 14 53 07](https://user-images.githubusercontent.com/2589111/50835092-0dbb3a80-1356-11e9-8558-23efe2908146.png)

The README used to be there, I know it moved, I know I can view it via `texdoc -l hyperref` and selecting "11" but this opens it in a pager in my console, which is inconvenient for search (or at least less convenient than it was in PDF format).

**Comment by jfbu** [comment]
EDIT the README.md opening in the pager is not at all the README I am thinking of, sorry.

**Comment by jfbu** [comment]
is the former README now `5 New Features` in `manual.pdf` ?

**Comment by u-fischer** [comment]
The readme.pdf and the manual.pdf have been merged.  So readme.pdf is gone and the one page you are mentioning is wrong.

**Comment by davidcarlisle** [comment]
Ah sorry I'll fix for next time.

Yes almost all the "new" (last decade or so) features were only documented
in readme.pdf and not in eh manual (as shown by texdoc hyperref) so I
merged the text in but clearly missed some links.

**Comment by jfbu** [comment]
thanks (both) I see now (again) the footnote "3 This section moved from the README file, needs more integration into the manual" from section New Features. Could it be possible to name it "New Features (formerly README)" for old-timers like myself with old habits?

btw typo in section Limitations, (10 Limitiations in  TOC)

**Comment by u-fischer** [comment]
i think this has been resolved.
