### ISSUE TITLE
\TextField has no height inside an array/matrix

### ISSUE THREAD

**Issue by daleif** [ho-tex/hyperref#84]
Below is a small MWE

As discussed in TSE chat, this is presumably because `\baselineskip` is zero inside array.

A default height set to `\normalbaselineskip` would probably be a good idea.

https://chat.stackexchange.com/transcript/message/49128457#49128457

```
\documentclass[a4paper]{article}
\usepackage[]{hyperref}
\parskip=1em
\newcommand\BOX[1]{\textrm{\TextField[name=#1,width=15mm]{}}}
\begin{document}
\begin{Form}
\[
\begin{array}{cc}
  1 & 2 \\
  \BOX{test1} & 4
\end{array}
\]

Test2: \BOX{test2}

\end{Form}
\end{document}
```

**Comment by u-fischer** [comment]
I changed to \normalbaselineskip.
