### ISSUE TITLE
Link to bugtracker in the manual

### ISSUE THREAD

**Issue by daleif** [ho-tex/hyperref#85]
Wouldn't it make sense to add the link to the bug tracker in the hyperref (and friends) manuals. At least it is not listed in 

```
doc/latex/hyperref/manual.pdf
```
AFAICS there is a link to the tracker in `../hyperref.pdf`, but `manual.pdf` is the default choice for `texdoc` in TL18.

**Comment by u-fischer** [comment]
I added a sentence in the introduction.
