### ISSUE TITLE
Loading hyperref incorrectly overrides PDF Producer

### ISSUE THREAD

**Issue by khaledhosny** [ho-tex/hyperref#91]
Merely loading hyperref with no other changes, and processing the document with [HarfTeX](https://github.com/khaledhosny/harftex) changes the PDF producer from `HarfTeX-0.1.1` to `LuaTeX-1.10.1`.
```tex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
Test
\end{document}
```

Without `hyperef`:
```
Creator:        TeX
Producer:       HarfTeX-0.1.1
CreationDate:   Fri Apr 26 19:56:50 2019 EET
ModDate:        Fri Apr 26 19:56:50 2019 EET
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      595.276 x 841.89 pts (A4)
Page rot:       0
File size:      2977 bytes
Optimized:      no
PDF version:    1.5
```

With `hyperref`:
```
Title:          
Subject:        
Keywords:       
Author:         
Creator:        LaTeX with hyperref
Producer:       LuaTeX-1.10.1
CreationDate:   Fri Apr 26 19:54:35 2019 EET
ModDate:        Fri Apr 26 19:54:35 2019 EET
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      3176 bytes
Optimized:      no
PDF version:    1.5
```

**Comment by davidcarlisle** [comment]
So it does, we could presumably detect harftex and change this, but given that luatex populates the /Producer field anyway it's not clear that hyperref over-writing it by default really helps. It's perhaps a bit different for the original latex/dvips/distiller|ps2pdf route where it is changing the default value.

Specifically I suspect this could be removed from `hluatex.def` 


```
    \begingroup
      \count@=\luatexversion
      \divide\count@ by 100 %
      \edef\x{\the\count@}%
      \count@=-\x\relax
      \multiply\count@ by 100 %
      \advance\count@ by \luatexversion
      \edef\x{\endgroup
        \def\noexpand\@pdfproducer{%
          LuaTeX-\x.\two@digits\count@.\luatexrevision
        }%
      }%
    \x
```

@u-fischer ?

**Comment by u-fischer** [comment]
Well that's certainly part of the "review pdf resources projekt". Looking at the default output and the one forced by hyperref, I would say that hyperref should at most change the producer for dvips and xetex. All other changes are either unneeded or worse than the default. Perhaps it would be even the best to remove all the settings and leave it to the user, if he wants to change something. 

@davidcarlisle ?
 
/Producer(GPL Ghostscript 9.26) -> /Producer(dvips + GPL Ghostscript 9.26)
/Producer (pdfTeX-1.40.20) -> /Producer(pdfTeX-1.40.20)
/Producer (LuaTeX-1.10.0) ->Producer(LuaTeX-1.10.0)
/Producer (MiKTeX pdfTeX-1.40.20) -> Producer(pdfTeX-1.40.20)
/Producer(xdvipdfmx \(20190225\))  -> /Producer(XeTeX 0.999991) , /Producer(dvipdfm)

**Comment by josephwright** [comment]
On the specific question: we should drop fiddling with `/Producer` unless requested. (Aside: I suspect we might also want to look at `/Creator`).

There's a general question here, which I've logged as https://github.com/latex3/latex3/issues/567.

**Comment by khaledhosny** [comment]
IMHO, hyperref (or any other package) shouldn’t be changing PDF metadata unless it has to or was explicitly asked to do so.

**Comment by josephwright** [comment]
@khaledhosny Well `/Creator` is inconsistent between engines (compare XeTeX with pdfTeX, for example). I think arguably LaTeX itself should set this one: 'LaTeX2e YYYY-MM-DD' would be reasonable.

**Comment by khaledhosny** [comment]
Yes, that would be reasonable for LaTeX code to do, not so much for individual packages.

**Comment by davidcarlisle** [comment]
remove them all I would say. Only the dvips one is at all useful and it
would be simpler to be consistent and not do any I think. @Joseph Wright
(CHE) <joseph.wright@morningstar2.co.uk>  ?

**Comment by u-fischer** [comment]
I removed the setting of the producer  field from the drivers. The next hyperref version will give 
`/Producer (HarfTeX-0.1.1)` for your example.
