### ISSUE TITLE
texorpdfstring breaks in sections with glossary conditionals

### ISSUE THREAD

**Issue by DenMesh** [ho-tex/hyperref#92]
MWE:
```
\documentclass[a4paper,oneside]{article}

\usepackage{glossaries}
\usepackage{hyperref}
\makeglossaries

\newglossaryentry{test}{
	name = test,
	description = test
}

\begin{document}
	\section{\texorpdfstring{\ifglshasfield{name}{test}{has}{has not}}{}} % Fails!
\end{document}
```

I have a helper macro in my document that checks for missing keys and/or entries in the glossary. Unfortunately, I can not avoid using it in section titles. Long story short, the MWE above fails with "Undefined control sequence" error. As far as I could determine, only this combo fails. Also, it does so only when the code for bookmarks is called:
```
\section[]{\texorpdfstring{\ifglshasfield{name}{test}{has}{has not}}{}} % Compiles!
```
Any help would be very much appreciated.

**Comment by dbitouze** [comment]
It should be enough to protect the `\ifglshasfield` command:

`\section{\texorpdfstring{\protect\ifglshasfield{name}{test}{has}{has not}}{}}`

**Comment by u-fischer** [comment]
`\section{\ifglshasfield{name}{test}{has}{has not}} ` breaks also without hyperref. As @dbitouze wrote, you need to protect such fragile commands in header titles or use the optional argument if the command is not meant for the toc anyway: `\section[some text for the toc]{\ifglshasfield{name}{test}{has}{has not}}`.
