### ISSUE TITLE
\TextField and \ChoiceMenu do not begin at the start of the line when there is no text before

### ISSUE THREAD

**Issue by CarLaTeX** [ho-tex/hyperref#93]
Even if the `\TextField` and `\ChoiceMenu` are the first objects in a line with `\noindent`, they don't begin and the start of the line, there is a little gap. 

See this post on TeX.SE: https://tex.stackexchange.com/questions/489283/why-dont-textfield-and-choicemenu-begin-at-the-start-of-the-line.

`\documentclass{article}
\usepackage{hyperref}
\usepackage{showframe}

\begin{document}
\begin{Form}[action=mailto:my_email@gmail.com?subject={The submitted form},encoding=html, method=post]
\noindent Why doesn't the following field begin at the start of the line?
\vspace{1ex}

\noindent\TextField[name=a,width=5cm,charsize=8pt, height=.5cm]{}
\vspace{4ex}

\noindent Adding \texttt{bordersep=0pt} doesn't help: 
\vspace{1ex}

\noindent\TextField[bordersep=0pt,name=b,width=5cm, height=.5cm]{}
\vspace{4ex}

\noindent The same with a choice menu:
\vspace{1ex}

\noindent\ChoiceMenu[combo, name=choice, width=5cm]{}{Choice 1, Choice 2}
\end{Form}
\end{document}`

**Comment by u-fischer** [comment]
I changed the definitions, the default now test for empty labels and then suppress the space.
