### ISSUE TITLE
hyperref  compilation problem

### ISSUE THREAD

**Issue by GartekPL** [ho-tex/hyperref#96]
I have a problem with combination: TeXLive+TeXStudio+win10 and the hyperref package. While loading the package \usepackage{hyperref} (even not using it) I got the following error: _hyperref.sty error line 36 Undefined control sequence. Hypertext links for LaTeX]_

I know it is just the lines 34-36 in hyperref.sty

34 _\ProvidesPackage{hyperref}_

35 _[2018/11/30 v6.88e %_

36 _Hypertext links for LaTeX]_

Please help!! I just reinstalled both TeXlive and TeXstudio and the error still the same.

**Comment by u-fischer** [comment]
It is impossible to help you if you don't provide a complete, minimal example showing the error and the log-file.

**Comment by GartekPL** [comment]
Thank that you tried to help. I found the problem, and it turned out that _\prefixing_ command before _\usepackage{hyperref}_ coses the issue. Have no idea why but it did.

**Comment by davidcarlisle** [comment]
This is really a bug report tracker (tex.stackexchange might have been
better) but please show a small example and the full log,
